services:
  gestionale-area41:
    image: node:24-alpine
    container_name: gestionale-area41
    working_dir: /app
    command: sh -c "npm install && node server.js"
    ports:
      - "3000:3000"
    volumes:
      - gestionale_area41_data:/app
    restart: unless-stopped

volumes:
  gestionale_area41_data: