services:
  gestionale-area41:
    build: .
    container_name: gestionale-area41
    ports:
      - "3000:3000"
    volumes:
      - gestionale_database:/app/database.json
      - gestionale_users:/app/users.json
      - gestionale_backup:/app/backup
      - gestionale_uploads:/app/uploads
    restart: unless-stopped

volumes:
  gestionale_database:
  gestionale_users:
  gestionale_backup:
  gestionale_uploads: